initial scripts based on examples

diff --git a/s2i/bin/assemble b/s2i/bin/assemble
--- a/s2i/bin/assemble
+++ b/s2i/bin/assemble
@@ -2,4 +2,28 @@
 source /opt/app-root/etc/gradle_environment
 
 echo "---> Installing application source ..."
-mv /tmp/src/* ./
+
+cp -ad /tmp/src/* ./
+
+if [ -f "./gradlew" ]; then
+    GRADLE_CMD="./gradlew"
+else
+    GRADLE_CMD="gradle"
+fi
+
+if [ -z "$BUILDER_ARGS" ]; then
+    export BUILDER_ARGS="build -x test"
+fi
+
+echo "Gradle version:"
+$GRADLE_CMD --version
+
+# Execute the actual build
+$GRADLE_CMD -s $BUILDER_ARGS
+
+ERR=$?
+if [ $ERR -ne 0 ]; then
+    echo "Aborting due to error code $ERR from Gradle build"
+    exit $ERR
+fi
+
